//! ffi-core API tests against fixtures/ (generated by fixtures/gen_fixtures.py).

use ffi_core::*;

fn fixture(name: &str) -> Vec<u8> {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../fixtures/");
    std::fs::read(format!("{path}{name}")).unwrap_or_else(|e| panic!("fixture {name}: {e}"))
}

// ---------------------------------------------------------------- normal

#[test]
fn process_normal_pdf() {
    let data = fixture("normal.pdf");
    let r = process_pdf_mem(&data).expect("process_pdf_mem");
    assert_eq!(r.pdf_type, FfiPdfType::TextBased);
    assert_eq!(r.page_count, 2);
    let md = r.markdown.expect("markdown populated in Full mode");
    assert!(md.contains("FFI Core Fixture"), "markdown: {md}");
    assert!(md.contains("Second Page Heading"), "markdown: {md}");
    assert!(r.pages_needing_ocr.is_empty());
    assert!(!r.has_encoding_issues);
    assert!(r.confidence > 0.0 && r.confidence <= 1.0);
}

#[test]
fn detect_normal_pdf() {
    let data = fixture("normal.pdf");
    let r = detect_pdf_mem(&data).expect("detect_pdf_mem");
    assert_eq!(r.pdf_type, FfiPdfType::TextBased);
    assert_eq!(r.page_count, 2);
    // DetectOnly mode: no markdown produced.
    assert!(r.markdown.is_none());
}

#[test]
fn classify_normal_pdf() {
    let data = fixture("normal.pdf");
    let c = classify_pdf_mem(&data).expect("classify_pdf_mem");
    assert_eq!(c.pdf_type, FfiPdfType::TextBased);
    assert_eq!(c.page_count, 2);
    assert!(c.pages_needing_ocr.is_empty());
    assert!(c.confidence > 0.0 && c.confidence <= 1.0);
}

#[test]
fn extract_pages_all_and_subset() {
    let data = fixture("normal.pdf");

    let all = extract_pages_markdown_mem(&data, None).expect("all pages");
    assert_eq!(all.pages.len(), 2);
    assert_eq!(all.pages[0].page, 0); // 0-indexed
    assert!(all.pages[0].markdown.contains("FFI Core Fixture"));
    assert!(!all.pages[0].needs_ocr);

    let sub = extract_pages_markdown_mem(&data, Some(&[1])).expect("page subset");
    assert_eq!(sub.pages.len(), 1);
    assert_eq!(sub.pages[0].page, 1);
    assert!(sub.pages[0].markdown.contains("Second Page Heading"));
}

// ---------------------------------------------------------------- malformed

/// Malformed inputs must return Err — never abort, never unwind across FFI.
#[test]
fn truncated_pdf_returns_error_not_abort() {
    let data = fixture("truncated.pdf");
    // Classification-level entries may still succeed on a valid header;
    // the contract is only "no abort". Full extraction must not panic either.
    for r in [
        process_pdf_mem(&data).map(|_| ()),
        detect_pdf_mem(&data).map(|_| ()),
        classify_pdf_mem(&data).map(|_| ()),
        extract_pages_markdown_mem(&data, None).map(|_| ()),
    ] {
        if let Err(e) = r {
            assert_ne!(e.code, FfiErrorCode::InternalPanic, "panic leaked: {e}");
        }
    }
}

#[test]
fn garbage_bytes_are_not_a_pdf() {
    let data = fixture("garbage.bin");
    let e = process_pdf_mem(&data).expect_err("garbage must fail");
    assert_eq!(e.code, FfiErrorCode::NotAPdf, "got {e}");
    assert!(classify_pdf_mem(&data).is_err());
    assert!(extract_pages_markdown_mem(&data, None).is_err());
}

#[test]
fn empty_and_tiny_inputs() {
    for data in [Vec::new(), b"%PDF".to_vec(), b"%PDF-1.7\n".to_vec()] {
        let r = process_pdf_mem(&data);
        assert!(r.is_err(), "len {} must fail", data.len());
        let e = r.unwrap_err();
        assert_ne!(e.code, FfiErrorCode::InternalPanic, "panic leaked: {e}");
    }
}

// ---------------------------------------------------------------- encrypted

#[test]
fn encrypted_pdf_maps_to_encrypted() {
    let data = fixture("encrypted.pdf");
    for r in [
        process_pdf_mem(&data).map(|_| ()),
        classify_pdf_mem(&data).map(|_| ()),
        extract_pages_markdown_mem(&data, None).map(|_| ()),
    ] {
        let e = r.expect_err("encrypted PDF must fail without password");
        assert_eq!(e.code, FfiErrorCode::Encrypted, "got {e}");
    }
}

// ---------------------------------------------------------------- fuzz-ish

/// Deterministic mutations of a valid PDF: bit flips, truncations at every
/// 64-byte boundary. Asserts the FFI contract: Ok or typed Err, never
/// InternalPanic (a panic here means catch_unwind caught an upstream bug
/// we need to know about — or worse, an abort).
#[test]
fn mutated_pdfs_never_panic() {
    let base = fixture("normal.pdf");
    let mut inputs: Vec<Vec<u8>> = Vec::new();

    for cut in (64..base.len()).step_by(64) {
        inputs.push(base[..cut].to_vec());
    }
    for i in (0..base.len()).step_by(97) {
        let mut m = base.clone();
        m[i] ^= 0xFF;
        inputs.push(m);
    }
    // Deterministic LCG random garbage of varying lengths.
    let mut state: u64 = 0x1234_5678_9abc_def0;
    for len in [16usize, 100, 511, 1024, 4096] {
        let mut v = Vec::with_capacity(len);
        for _ in 0..len {
            state = state.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
            v.push((state >> 33) as u8);
        }
        inputs.push(v);
    }

    for (idx, data) in inputs.iter().enumerate() {
        for r in [
            process_pdf_mem(data).map(|_| ()),
            detect_pdf_mem(data).map(|_| ()),
            classify_pdf_mem(data).map(|_| ()),
            extract_pages_markdown_mem(data, None).map(|_| ()),
            extract_pages_markdown_mem(data, Some(&[0, 1, 7])).map(|_| ()),
        ] {
            if let Err(e) = r {
                assert_ne!(
                    e.code,
                    FfiErrorCode::InternalPanic,
                    "input #{idx} (len {}) triggered a caught panic: {e}",
                    data.len()
                );
            }
        }
    }
}

// ---------------------------------------------------------------- page OOB

#[test]
fn out_of_range_pages_error_cleanly() {
    let data = fixture("normal.pdf");
    let r = extract_pages_markdown_mem(&data, Some(&[5]));
    match r {
        // Upstream yields an empty page flagged needs_ocr for OOB requests.
        Ok(res) => assert!(
            res.pages.iter().all(|p| p.markdown.is_empty() && p.needs_ocr),
            "unexpected pages: {:?}",
            res.pages
        ),
        Err(e) => assert_ne!(e.code, FfiErrorCode::InternalPanic, "panic leaked: {e}"),
    }
}
