#!/usr/bin/env bash
# Vendor ffi-core into the Elixir package so the hex tarball is self-contained.
#
# The hex package only ships `elixir/`, so the NIF crate cannot keep pointing
# at `../../../ffi-core` (outside the package). This script syncs the canonical
# source (../../ffi-core) into elixir/native/ffi-core with the Cargo.toml
# workspace-inheritance fields flattened — the vendored copy must build
# standalone, with no parent workspace.
#
# Canonical source of truth remains the root ffi-core/ (Swift P1 uses it).
# Run after any ffi-core change; CI (P3) fails the build if the copy drifts.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/ffi-core"
DST="$ROOT/elixir/native/ffi-core"

mkdir -p "$DST"
rsync -a --delete "$SRC/src/" "$DST/src/"

# Flattened Cargo.toml: no `*.workspace = true` fields (no parent workspace
# in the hex package). Values mirror the root workspace.package table.
# NOTE: the package is renamed to ffi-core-vendored — two packages named
# ffi-core at the same version would collide in the monorepo Cargo.lock.
# The NIF crate imports it as `ffi_core` via a `package =` rename.
cat > "$DST/Cargo.toml" <<'EOF'
# GENERATED by scripts/vendor_ffi_core.sh — do not edit by hand.
# Synced from the canonical ../../../ffi-core (src/ copied verbatim;
# workspace-inherited fields flattened so this crate builds standalone).
# Renamed to ffi-core-vendored to avoid a Cargo.lock package collision
# with the canonical ffi-core in the monorepo workspace.
[package]
name = "ffi-core-vendored"
description = "Flat FFI facade over pdf-inspector (mem-only API) for Swift/Elixir bindings"
version = "0.1.0"
edition = "2021"
license = "MIT"
publish = false

[dependencies]
# Pinned to the crates.io release, no upstream fork.
pdf-inspector = "~1.17"
# UniFFI proc-macro bindings (P1). The CLI (`uniffi_bindgen` crate) must be
# the same version when generating Swift bindings.
uniffi = "0.32"
EOF

echo "vendored: $SRC -> $DST"
